services:
  postgres:
    image: postgres:18
    container_name: aliados-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aliados-net

  api:
    build: .
    container_name: aliados-api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:passw0rd0@postgres:5432/aliados360
    ports:
      - "3000:3000"
    networks:
      - aliados-net

volumes:
  postgres_data:

networks:
  aliados-net: