sonar.projectKey=nykt3r_aliados-360-api
sonar.organization=nykt3r
sonar.sources=src
sonar.tests=test
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/node_modules/**, src/app.ts, src/server.ts, src/config/**, src/domain/errors/**, **/*.spec.ts, test/**/*.spec.ts, **/infrastructure/**